# THE PURPOSE OF THIS SCRIPT IS TO VALIDATE THE OPTIONS THAT A PLAYER MAY TAKE AT ANY GIVEN TURN. 
# IN THE CONTEXT OF THE FIRST PHASE(YOU DRAW) SECOND PHASE(OPEN UP THE BOARD FOR OTHERS TO PLAY) WE DISCUSSED THIS WOULD COVER
# MOSTLY THE SECOND PHASE STUFF THOUGH IT CAN EXTENDED TO COVER FIRST PHASE IF NECESSARY